services:
  postgres:
    image: postgres:16-alpine
    container_name: moeda-estudantil-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: moeda_estudantil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

